name: hello_test
on: [push]

jobs:
  io_test:
  name: Use Linux commands
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
    uses: actions/checkout@v4
    - name: Permission Setting
    run: chmod +x hello.sh hello_test.sh
    - name: Test Run
      run: ./hello-test.sh
